### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tamsky** [tamsky/mac#1]
TODO

 - [ ]  migrate https://github.com/tamsky/dotfiles/blob/master/.emacs.d/mtamsky.el away from emascs-starter-kit.
 - [ ] merge https://github.com/tamsky/mac/blob/master/.Xresources into dotfiles

OLD
 - [ ] create bootstrap.sh
 - [ ] rename files with leading dot('.') to just capitalized (aka 'Bash_rc' vs '.bashrc')
